[CmdletBinding()]
param([ValidateSet("status","sync","verify","audit","evidence","recover")][string]$Command="status",[switch]$Json,[string]$RepoRoot=(Split-Path -Parent (Split-Path -Parent $PSScriptRoot)))
$ErrorActionPreference="Stop"; Set-StrictMode -Version Latest
$Root=(Resolve-Path $RepoRoot).Path; $EvidenceRoot=Join-Path $Root "evidence/recon-sync"; $RunId="recon-{0}" -f (Get-Date -Format "yyyyMMdd-HHmmss"); $RunDir=Join-Path $EvidenceRoot $RunId
function Invoke-Git([string[]]$Args){$o=& git.exe -C $Root @Args 2>&1;if($LASTEXITCODE -ne 0){throw "git failed: $($Args -join ' ') | $($o -join [Environment]::NewLine)};($o -join [Environment]::NewLine).Trim()}
function Result([string]$Status,[string]$Operation,[string]$Error=""){[ordered]@{status=$Status;operation=$Operation;run_id=$RunId;canonical_sha=$script:CanonicalSha;local_sha=$script:LocalSha;preservation_ref=$script:PreservationRef;worktree=$script:CleanWorktree;evidence=$RunDir;timestamp=(Get-Date).ToUniversalTime().ToString("o");errors=@($(if($Error){$Error}))}}
function Write-Result($r){New-Item -ItemType Directory -Force -Path $RunDir|Out-Null;$r|ConvertTo-Json -Depth 8|Set-Content (Join-Path $RunDir "result.json") -Encoding UTF8;if($Json){$r|ConvertTo-Json -Depth 8}else{"[$($r.status)] $($r.operation) $($r.run_id)";"Canonical : $($r.canonical_sha)";"Local     : $($r.local_sha)";"Evidence  : $($r.evidence)";$r.errors|ForEach-Object{if($_){"ERROR     : $_"}}}}
$script:CanonicalSha=Invoke-Git @("rev-parse","refs/remotes/canonical/main");$script:LocalSha=Invoke-Git @("rev-parse","HEAD");$script:PreservationRef="";$script:CleanWorktree=""
try{switch($Command){
"status"{$dirty=Invoke-Git @("status","--porcelain");Write-Result(Result ($(if($dirty){"DIRTY"}else{"PASS"}),"status"))}
"verify"{$remote=((Invoke-Git @("ls-remote","https://github.com/phakphum12345/ENTERPRISE_API_ARCHITECTURE_LOGIC_TH.git","refs/heads/main")) -split "s+")[0];if($remote -ne $CanonicalSha){throw "canonical/main changed during verification: $remote"};Write-Result(Result "PASS" "verify")}
"sync"{if(Invoke-Git @("status","--porcelain")){$script:PreservationRef="preserve/$RunId";Invoke-Git @("branch",$PreservationRef,"HEAD")|Out-Null};Invoke-Git @("fetch","canonical","main")|Out-Null;$script:CanonicalSha=Invoke-Git @("rev-parse","refs/remotes/canonical/main");$wt=Join-Path ([IO.Path]::GetDirectoryName($Root)) ("{0}-canonical-{1}" -f (Split-Path $Root -Leaf),$RunId);Invoke-Git @("worktree","add","--detach",$wt,$CanonicalSha)|Out-Null;$script:CleanWorktree=$wt;New-Item -ItemType Directory -Force -Path $RunDir|Out-Null;[ordered]@{run_id=$RunId;canonical_sha=$CanonicalSha;local_sha=$LocalSha;preservation_ref=$PreservationRef;clean_worktree=$wt}|ConvertTo-Json -Depth 8|Set-Content (Join-Path $RunDir "manifest.json") -Encoding UTF8;Write-Result(Result "PASS" "sync")}
"audit"{$forbidden=@("versions","artifact-*","forensic_*","workflow-intelligence-audit-*");$violations=@();$status=Invoke-Git @("status","--porcelain");foreach($line in ($status -split [Environment]::NewLine)){if(!$line){continue};$p=$line.Substring(3);foreach($f in $forbidden){if($p -like "$f*" -or $p -like "*/$f*"){$violations+=$p}}};if($violations.Count){throw "forbidden paths detected: $($violations -join ', ')"};Write-Result(Result "PASS" "audit")}
"evidence"{New-Item -ItemType Directory -Force -Path $RunDir|Out-Null;$m=[ordered]@{run_id=$RunId;canonical_sha=$CanonicalSha;local_sha=$LocalSha;timestamp=(Get-Date).ToUniversalTime().ToString("o")};$raw=$m|ConvertTo-Json -Depth 8;$raw|Set-Content (Join-Path $RunDir "canonical.json") -Encoding UTF8;$bytes=[Text.Encoding]::UTF8.GetBytes($raw);$sha=([Security.Cryptography.SHA256]::HashData($bytes)|ForEach-Object ToString x2)-join "";$e=@{run_id=$RunId;sha256=$sha;files=@("canonical.json")};$e|ConvertTo-Json -Depth 8|Set-Content (Join-Path $RunDir "evidence.json") -Encoding UTF8;Write-Result(Result "PASS" "evidence")}
"recover"{$latest=Get-ChildItem $EvidenceRoot -Directory -ErrorAction SilentlyContinue|Sort-Object Name -Descending|Select-Object -First 1;if(!$latest){throw "no Recon-Sync run exists to recover"};$script:RunId=$latest.Name;Write-Result(Result "PASS" "recover")}
}}catch{Write-Result(Result "FAIL" $Command $_.Exception.Message);exit 1}